name = "DominoPuzzleProof"
version = "0.1.0"
defaultTargets = ["blueprint-gen"]

[[require]]
name = "verso"
git = "https://github.com/ejgallego/verso.git"
rev = "a61eb8993e8d1a617a60c502020f95f3525e6c9d"

[[require]]
name = "VersoBlueprint"
git = "https://github.com/leanprover/verso-blueprint.git"
rev = "v4.30.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.30.0"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.30.0"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "v4.30.0"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.30.0"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "v0.0.99"

[[require]]
name = "importGraph"
git = "https://github.com/leanprover-community/import-graph"
rev = "v4.30.0"

[[require]]
name = "LeanSearchClient"
git = "https://github.com/leanprover-community/LeanSearchClient"
rev = "main"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.30.0"

[[lean_lib]]
name = "DominoPuzzleProof"

[[lean_exe]]
name = "blueprint-gen"
root = "BlueprintMain"
supportInterpreter = true
